<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class userseeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert(
            [
                [
                    'id' => 1,
                    'name' => 'budi setyawan',
                    'email' => 'budi@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 1,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901234',
                    'jenis_kelamin' => 'laki-laki',
                    'tempat_lahir' => 'surabaya',
                    'tanggal_lahir' => '2024-02-07',
                    'agama' => 'islam',
                    'pendidikan' => 'SMA',
                    'jenis_pekerjaan' => 'swasta',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 2,
                    'name' => 'siti aminah',
                    'email' => 'siti@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 1,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901235',
                    'jenis_kelamin' => 'perempuan',
                    'tempat_lahir' => 'jakarta',
                    'tanggal_lahir' => '1990-05-12',
                    'agama' => 'islam',
                    'pendidikan' => 'D3',
                    'jenis_pekerjaan' => 'PNS',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 3,
                    'name' => 'agus prasetyo',
                    'email' => 'agus@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 1,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901236',
                    'jenis_kelamin' => 'laki-laki',
                    'tempat_lahir' => 'bandung',
                    'tanggal_lahir' => '1985-08-23',
                    'agama' => 'protestan',
                    'pendidikan' => 'S1',
                    'jenis_pekerjaan' => 'pegawai swasta',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 4,
                    'name' => 'ria andini',
                    'email' => 'ria@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 1,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901237',
                    'jenis_kelamin' => 'perempuan',
                    'tempat_lahir' => 'medan',
                    'tanggal_lahir' => '1992-03-19',
                    'agama' => 'hindu',
                    'pendidikan' => 'SMA',
                    'jenis_pekerjaan' => 'wirausaha',
                    'status' => 'belum kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 5,
                    'name' => 'andi susanto',
                    'email' => 'andi@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 1,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901238',
                    'jenis_kelamin' => 'laki-laki',
                    'tempat_lahir' => 'yogyakarta',
                    'tanggal_lahir' => '1987-11-10',
                    'agama' => 'budha',
                    'pendidikan' => 'S1',
                    'jenis_pekerjaan' => 'dosen',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 6,
                    'name' => 'dwi handayani',
                    'email' => 'dwi@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 1,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901239',
                    'jenis_kelamin' => 'perempuan',
                    'tempat_lahir' => 'semarang',
                    'tanggal_lahir' => '1994-04-21',
                    'agama' => 'islam',
                    'pendidikan' => 'SMA',
                    'jenis_pekerjaan' => 'perawat',
                    'status' => 'belum kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 7,
                    'name' => 'rahmat hidayat',
                    'email' => 'rahmat@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 1,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901240',
                    'jenis_kelamin' => 'laki-laki',
                    'tempat_lahir' => 'makassar',
                    'tanggal_lahir' => '1991-12-01',
                    'agama' => 'islam',
                    'pendidikan' => 'S1',
                    'jenis_pekerjaan' => 'pegawai negeri',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 8,
                    'name' => 'sri wahyuni',
                    'email' => 'sri@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 1,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901241',
                    'jenis_kelamin' => 'perempuan',
                    'tempat_lahir' => 'palembang',
                    'tanggal_lahir' => '1986-07-15',
                    'agama' => 'protestan',
                    'pendidikan' => 'D3',
                    'jenis_pekerjaan' => 'sekretaris',
                    'status' => 'belum kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 9,
                    'name' => 'toni saputra',
                    'email' => 'toni@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 1,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901242',
                    'jenis_kelamin' => 'laki-laki',
                    'tempat_lahir' => 'medan',
                    'tanggal_lahir' => '1995-05-25',
                    'agama' => 'islam',
                    'pendidikan' => 'SMA',
                    'jenis_pekerjaan' => 'pengemudi',
                    'status' => 'belum kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 10,
                    'name' => 'rian saputra',
                    'email' => 'rian@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 1,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901242',
                    'jenis_kelamin' => 'laki-laki',
                    'tempat_lahir' => 'madura',
                    'tanggal_lahir' => '1990-05-25',
                    'agama' => 'islam',
                    'pendidikan' => 'SMA',
                    'jenis_pekerjaan' => 'sopir truk',
                    'status' => 'belum kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 11,
                    'name' => 'joko purnomo',
                    'email' => 'joko@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 2,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901243',
                    'jenis_kelamin' => 'laki-laki',
                    'tempat_lahir' => 'batam',
                    'tanggal_lahir' => '1989-02-18',
                    'agama' => 'islam',
                    'pendidikan' => 'SMA',
                    'jenis_pekerjaan' => 'pegawai swasta',
                    'status' => 'belum kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 12,
                    'name' => 'lina rahmawati',
                    'email' => 'lina@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 2,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901244',
                    'jenis_kelamin' => 'perempuan',
                    'tempat_lahir' => 'samarinda',
                    'tanggal_lahir' => '1996-04-15',
                    'agama' => 'protestan',
                    'pendidikan' => 'SMA',
                    'jenis_pekerjaan' => 'kasir',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 13,
                    'name' => 'dian permata',
                    'email' => 'dian@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 2,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901245',
                    'jenis_kelamin' => 'perempuan',
                    'tempat_lahir' => 'banda aceh',
                    'tanggal_lahir' => '1993-01-20',
                    'agama' => 'islam',
                    'pendidikan' => 'S1',
                    'jenis_pekerjaan' => 'guru',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 14,
                    'name' => 'tri wahyudi',
                    'email' => 'tri@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 2,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901246',
                    'jenis_kelamin' => 'laki-laki',
                    'tempat_lahir' => 'manado',
                    'tanggal_lahir' => '1988-09-11',
                    'agama' => 'protestan',
                    'pendidikan' => 'S2',
                    'jenis_pekerjaan' => 'dokter',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 15,
                    'name' => 'agus sulaiman',
                    'email' => 'agus.sulaiman@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 2,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901247',
                    'jenis_kelamin' => 'laki-laki',
                    'tempat_lahir' => 'denpasar',
                    'tanggal_lahir' => '1990-12-08',
                    'agama' => 'hindu',
                    'pendidikan' => 'S1',
                    'jenis_pekerjaan' => 'pegawai bank',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 16,
                    'name' => 'nina susanti',
                    'email' => 'nina@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 2,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901248',
                    'jenis_kelamin' => 'perempuan',
                    'tempat_lahir' => 'jambi',
                    'tanggal_lahir' => '1985-07-22',
                    'agama' => 'islam',
                    'pendidikan' => 'SMA',
                    'jenis_pekerjaan' => 'pedagang',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 17,
                    'name' => 'bagus pratama',
                    'email' => 'bagus@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 2,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901249',
                    'jenis_kelamin' => 'laki-laki',
                    'tempat_lahir' => 'palu',
                    'tanggal_lahir' => '1994-10-05',
                    'agama' => 'protestan',
                    'pendidikan' => 'S1',
                    'jenis_pekerjaan' => 'pegawai BUMN',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 18,
                    'name' => 'siska wijaya',
                    'email' => 'siska@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 2,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901250',
                    'jenis_kelamin' => 'perempuan',
                    'tempat_lahir' => 'pontianak',
                    'tanggal_lahir' => '1987-04-30',
                    'agama' => 'islam',
                    'pendidikan' => 'S2',
                    'jenis_pekerjaan' => 'pengusaha',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 19,
                    'name' => 'bambang susanto',
                    'email' => 'bambang@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 2,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901251',
                    'jenis_kelamin' => 'laki-laki',
                    'tempat_lahir' => 'makassar',
                    'tanggal_lahir' => '1984-11-17',
                    'agama' => 'islam',
                    'pendidikan' => 'SMA',
                    'jenis_pekerjaan' => 'pilot',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ],
                [
                    'id' => 20,
                    'name' => 'dedi kurniawan',
                    'email' => 'dedi@gmail.com',
                    'email_verified_at' => null,
                    'password' => password_hash('12345678', PASSWORD_DEFAULT),
                    'level_users_id' => 5,
                    'domisilis_id' => 2,
                    'kependudukan' => 'warga tetap',
                    'no_KK' => '2345678901252',
                    'jenis_kelamin' => 'laki-laki',
                    'tempat_lahir' => 'gorontalo',
                    'tanggal_lahir' => '1992-11-30',
                    'agama' => 'islam',
                    'pendidikan' => 'SMA',
                    'jenis_pekerjaan' => 'pelaut',
                    'status' => 'kawin',
                    'profile' => '',
                    'remember_token' => '',
                    'created_at' => now(),
                    'updated_at' => now()
                ]

            ]
        );
    }
}
